databases:
  - name: hello
    databaseName: hello
    user: hello

services:
  - type: web
    name: hello
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn hello.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hello
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4